""" this document defines the users app urls """
from django.conf.urls import url, include
from . import views
from users.views import UserCreateView

accounts_patterns = [
    url(
        r'^login/$',
        'users.views.login',
        name='login'
    ),
    url(
        r'^most-active/$',
        views.PeopleListView.as_view(),
        name='participants_list'
    ),
    url(
        r'^password-change/$',
        'users.views.password_change',
        name='password_change'
    ),
    url(
        r'^logout/$',
        'users.views.logout',
        name='logout'
    ),
    url(
        r'^register/$',
        views.RegisterView.as_view(),
        name='register',
    ),
    url(
        r'^register/success/$',
        views.RegisterSuccessView.as_view(),
        name='register_success',
    ),
    url(
        r'^password-email-sent/$',
        'users.views.password_reset_email_sent',
        name='password_email_sent'
    ),
    url(
        r'^password-reset/$',
        'users.views.password_reset',
        name='password_reset'
    ),
    url(
        r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        'users.views.password_reset_confirm',
        name='password_reset_confirm'
    ),
    url(
        r'^create/$',
        UserCreateView.as_view(),
        name='user_create'
    ),
    url(
        r'^verify/(?P<uidb36>[0-9A-Za-z]{1,13})-'
        '(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'users.views.user_new_confirm',
        name='user_new_confirm'
    ),
    url(
        r'^reset/done/$',
        'users.views.password_reset_complete',
        name='password_reset_complete'
    ),
    url(
        r'^edit/$',
        views.UserUpdateView.as_view(),
        name='user_update'
    ),
    url(
        r'^edit/profile/$',
        views.UserProfileUpdateView.as_view(),
        name='user_profile_update'
    ),
    url(
        r'^edit/avatar/$',
        views.UserAvatarUpdateView.as_view(),
        name='user_avatar_update'
    ),
    url(
        r'^edit/password/$',
        views.UserPasswordUpdateView.as_view(),
        name='user_password_update'
    ),
    url(
        r'^edit/account/$',
        views.UserAccountUpdateView.as_view(),
        name='user_account_update'
    ),
    url(
        r'^edit/image/(?P<user_pk>\d+)/$',
        views.UserEditImageView.as_view(),
        name='user_edit_image'
    ),
    url(
        r'^profile/$',
        views.ParticipantDetailView.as_view(),
        name='user_profile'
    ),
    url(
        r'^deactivate/(?P<user_pk>\d+)/$',
        'users.views.deactivate',
        name='deactivate'
    ),
    url(
        r'^send-message/(?P<user_pk>\d+)/$',
        'users.views.send_message',
        name='send_message'
    ),
    url(r'^delete/(?P<user_pk>\d+)/$',
        views.DeleteAccountRedirectView.as_view(),
        name='delete_account_redirect_view',
    ),
    url(r'^(?P<user_pk>\d+)/send-recover-password/$',
        views.send_recover_password_email,
        name='send_recover_password_email',
    ),
    url(r'^terms/$',
        'users.views.terms',
        name='terms',
    ),
    url(r'^whats/$',
        'users.views.whats',
        name='whats',
    ),
]

participants_patterns = [
    url(
        r'^people/$',
        views.PeopleListView.as_view(),
        name='people_list',
    ),
    url(
        r'^people/accepted/$',
        views.ParticipantListView.as_view(),
        name='participant_list',
    ),
    url(
        r'^people/pending/$',
        views.PendingParticipantListView.as_view(),
        name='pending_participant_list',
    ),
    url(
        r'^people/rejected/$',
        views.RejectedParticipantListView.as_view(),
        name='rejected_participant_list',
    ),
    url(
        r'^people/extern/$',
        views.ExternParticipantListView.as_view(),
        name='extern_participant_list',
    ),
    url(
        r'^people/accept/(?P<user_pk>\d+)/$',
        views.AcceptUserRedirectView.as_view(),
        name='accept_user_redirect_view'
    ),
    url(
        r'^people/accept-staff/(?P<user_pk>\d+)/$',
        views.AcceptStaffUserRedirectView.as_view(),
        name='accept_staff_user_redirect_view'
    ),
    url(
        r'^people/remove-staff/(?P<user_pk>\d+)/$',
        views.RemoveStaffUserRedirectView.as_view(),
        name='remove_staff_user_redirect_view'
    ),
    url(
        r'^people/accept-extern/(?P<user_pk>\d+)/$',
        views.AcceptExternUserRedirectView.as_view(),
        name='accept_extern_user_redirect_view'
    ),
    url(
        r'^people/reject/(?P<user_pk>\d+)/$',
        views.RejectUserRedirectView.as_view(),
        name='reject_user_redirect_view'
    ),
    url(
        r'^people/admin/$',
        views.UserAdminListView.as_view(),
        name='user_admin_list_view',
    ),
    url(
        r'^people/export/$',
        views.export_users,
        name='export_users',
    ),
    url(
        r'^people/pk(?P<pk>[\d-]+)/$',
        views.ParticipantDetailView.as_view(),
        name='participant_detail',
    ),
    url(
        r'^people/(?P<slug>[\w-]+)/$',
        views.ParticipantDetailView.as_view(),
        name='participant_detail',
    ),
    url(
        r'^people/update/(?P<pk>\d+)/$',
        views.ParticipantUserUpdateView.as_view(),
        name='participant_user_update',
    ),
    url(
        r'^people/update/(?P<pk>\d+)/profile/$',
        views.ParticipantProfileUpdateView.as_view(),
        name='participant_profile_update'
    ),
    url(
        r'^people/update/(?P<pk>\d+)/avatar/$',
        views.ParticipantAvatarUpdateView.as_view(),
        name='participant_avatar_update'
    ),
    url(
        r'^people/update/(?P<pk>\d+)/password/$',
        views.ParticipantPasswordUpdateView.as_view(),
        name='participant_password_update'
    ),
    url(
        r'^people/update/(?P<pk>\d+)/account/$',
        views.ParticipantAccountUpdateView.as_view(),
        name='participant_account_update'
    ),
    url(
        r'^people/admin/add/(?P<user_pk>\d+)/$',
        views.AddAdminRedirectView.as_view(),
        name='add_admin_redirect'
    ),
    url(
        r'^people/admin/delete/(?P<user_pk>\d+)/$',
        views.DeleteAdminRedirectView.as_view(),
        name='delete_admin_redirect'
    ),
]

urlpatterns = [
    url(r'^accounts/', include(accounts_patterns)),
    url(r'^participants/', include(participants_patterns)),
]
